-- AleScript Grammar for BNFC
-- Converted to proper BNFC syntax

-- Token definitions
token Identifier (letter | '_') (letter | digit | '_')* ;
token Number digit+ | digit+ '.' digit+ ;
token Percentage digit+ ('.' digit+)? '%' ;
token StringLit '"' ((char - ["\"\\"]) | ('\\' char))* '"' ;

comment "//" ;

-- List separators
separator Statement "" ;
separator nonempty Ingredient "," ;
separator nonempty Identifier "," ;
separator nonempty Expression "," ;

-- Top-level program
Prog. Program ::= [Statement] ;

-- Statement types
SBrewDecl. Statement ::= BrewDecl ;
SWaitStmt. Statement ::= WaitStmt ;
STasteStmt. Statement ::= TasteStmt ;
SToastStmt. Statement ::= ToastStmt ;
SAgeStmt. Statement ::= AgeStmt ;
SBlendStmt. Statement ::= BlendStmt ;
SFortifyStmt. Statement ::= FortifyStmt ;
SFilterStmt. Statement ::= FilterStmt ;
SConditional. Statement ::= Conditional ;
SLoop. Statement ::= Loop ;
SKegStmt. Statement ::= KegStmt ;
SBarrelDecl. Statement ::= BarrelDecl ;
SBarrelAdd. Statement ::= BarrelAdd ;
SBarrelRemove. Statement ::= BarrelRemove ;
SRecipeDecl. Statement ::= RecipeDecl ;
SRecipeCallStmt. Statement ::= RecipeCallStmt ;
SRelabelStmt. Statement ::= RelabelStmt ;
SReturnStmt. Statement ::= ReturnStmt ;
SComment. Statement ::= Comment ;

-- Brew declarations
BrewFrom. BrewDecl ::= "brew" Identifier "from" [Ingredient] "." ;
BrewExpr. BrewDecl ::= "brew" Identifier "=" Expression "." ;

-- Ingredients
SimpleIngredient. Ingredient ::= IngredientName ;
QuantifiedIngredient. Ingredient ::= Number IngredientName ;

Water. IngredientName ::= "water" ;
Barley. IngredientName ::= "barley" ;
Hops. IngredientName ::= "hops" ;
Yeast. IngredientName ::= "yeast" ;

-- Wait statements
WaitDays. WaitStmt ::= "wait" "for" Number "days" "." ;
WaitDay. WaitStmt ::= "wait" "for" Number "day" "." ;

-- Age statement
Age. AgeStmt ::= "age" Identifier "until" Percentage "." ;

-- Taste statement
Taste. TasteStmt ::= "taste" Identifier "." ;

-- Toast statement
Toast. ToastStmt ::= "toast" Expression "." ;

-- Blend statement
Blend. BlendStmt ::= "blend" Identifier "with" Identifier "." ;

-- Fortify statement
Fortify. FortifyStmt ::= "fortify" Identifier "by" Number "." ;

-- Filter statement
Filter. FilterStmt ::= "filter" Identifier "by" Number "." ;

-- Keg statement
Keg. KegStmt ::= "keg" Identifier "." ;

-- Conditionals
CondIf. Conditional ::= IfStmt ;
CondJudge. Conditional ::= JudgeStmt ;

IfSimple. IfStmt ::= "if" Comparison ":" [Statement] "end" "." ;
IfElse. IfStmt ::= "if" Comparison ":" [Statement] "else" ":" [Statement] "end" "." ;

JudgeSimple. JudgeStmt ::= "judge" "if" Comparison ":" [Statement] "end" "." ;
JudgeElse. JudgeStmt ::= "judge" "if" Comparison ":" [Statement] "else" ":" [Statement] "end" "." ;

-- Comparisons
CompIs. Comparison ::= Identifier "is" Percentage ;
CompStronger. Comparison ::= Identifier "is" "stronger" "than" Percentage ;
CompWeaker. Comparison ::= Identifier "is" "weaker" "than" Percentage ;
CompNotWeaker. Comparison ::= Identifier "is" "not" "weaker" "than" Percentage ;
CompNotStronger. Comparison ::= Identifier "is" "not" "stronger" "than" Percentage ;
CompIsNumber. Comparison ::= Identifier "is" Number ;

-- Loops
RepeatUntil. Loop ::= "repeat" "until" Comparison ":" [Statement] "end" "." ;
RepeatTimes. Loop ::= "repeat" Expression "times" ":" [Statement] "end" "." ;
RepeatEach. Loop ::= "repeat" "each" Identifier "in" Identifier ":" [Statement] "end" "." ;

-- Barrel operations
BarrelDef. BarrelDecl ::= "barrel" Identifier "=" "[" [Identifier] "]" "." ;

BarrelAddOp. BarrelAdd ::= "add" Identifier "to" Identifier "." ;

BarrelRemoveOp. BarrelRemove ::= "remove" Identifier "from" Identifier "." ;

BarrelPos. BarrelAccess ::= Identifier "position" Number ;

-- Recipe declarations and calls
RecipeDef. RecipeDecl ::= "recipe" Identifier "(" [Identifier] ")" [Statement] "end" "." ;

RecipeStmt. RecipeCallStmt ::= RecipeCall "." ;

RecCall. RecipeCall ::= Identifier "(" [Expression] ")" ;

-- Relabel statement
Relabel. RelabelStmt ::= "relabel" Identifier "as" Expression "." ;

-- Return statement
Return. ReturnStmt ::= Identifier ;

-- Comment (handled by comment directive)
CommentStmt. Comment ::= ;

-- Expressions
EIdentifier. Expression ::= Identifier ;
ENumber. Expression ::= Number ;
EString. Expression ::= StringLit ;
EPercentage. Expression ::= Percentage ;
ERecipeCall. Expression ::= RecipeCall ;
EBarrelAccess. Expression ::= BarrelAccess ;
